/* ---------------------------------------------------------------
   Team Roster — single source of truth for users + roles
   --------------------------------------------------------------- */
const TEAM_ROSTER = [
  {
    name: "Jnuru Goodwin",
    email: "jnurugoodwin48@gmail.com",
    initials: "JG",
    primaryRole: "Builder",
    isAdmin: true,
    defaultView: "my_work",
    inviteKey: "jnuru",
  },
  {
    name: "Scott Touloo",
    email: "scott.touloo@fusz.com",
    initials: "ST",
    primaryRole: "AEO Writer",
    isAdmin: true,
    defaultView: "my_work",
    inviteKey: "scott",
  },
  {
    name: "Chris Pajda",
    email: "chris.pajda@fusz.com",
    initials: "CP",
    primaryRole: "SEO Writer",
    isAdmin: false,
    defaultView: "my_work",
    inviteKey: "chris",
  },
];

function rosterByEmail(email) {
  return TEAM_ROSTER.find((m) => m.email.toLowerCase() === (email || "").toLowerCase()) || null;
}

function rosterByInviteKey(key) {
  return TEAM_ROSTER.find((m) => m.inviteKey === (key || "").toLowerCase()) || null;
}

const statusLabels = {
  needs_seo: "Needs SEO",
  seo_in_progress: "SEO in progress",
  seo_done: "SEO ready",
  needs_build: "Ready to build",
  page_built: "Built — verify",
  live: "Live",
  ignored: "Ignored",
  snoozed: "Snoozed",
  needs_review: "Returned",
};

const aeoLabels = {
  not_started: "AEO pending",
  in_progress: "AEO in progress",
  done: "AEO done",
  not_needed: "AEO not needed",
};

const signalLabels = {
  upcoming: "Upcoming",
  shipped: "Shipped",
  on_lot: "On lot",
};

const dealerAccents = {
  "Lou Fusz Chrysler Jeep Dodge RAM": "#8f98a3",
  "Lou Fusz Mazda": "#808080",
  "Lou Fusz Toyota": "#eb0a1e",
  "Lou Fusz Buick GMC": "#005daa",
  "Lou Fusz Chevrolet": "#c8a95a",
  "Lou Fusz Kia": "#05141F",
  "Lou Fusz Ford": "#003478",
  "Lou Fusz Chrysler Jeep Dodge Ram Vincennes": "#8f98a3",
  "Lou Fusz Kia Evansville": "#05141F",
  "Lou Fusz Kia of Moline": "#05141F",
  "Lou Fusz Kia Terre Haute": "#05141F",
  "Lou Fusz Mazda Evansville": "#808080",
  "Lou Fusz Nissan Moline": "#c3002f",
  "Lou Fusz Subaru St. Louis": "#013c74",
  "Lou Fusz Subaru O'Fallon": "#013c74",
  "Lou Fusz Kia Columbus": "#05141F",
};

const brandAccentOverrides = {
  Kia:       { accent: "#05141F", visible: "#05141F", ink: "#d7e6f2" },
  Mazda:     { accent: "#808080", visible: "#808080", ink: "#eeeeee" },
  Chrysler:  { accent: "#203B68", visible: "#203B68", ink: "#c9dcff" },
  Dodge:     { accent: "#DA0000", visible: "#DA0000", ink: "#ffd1d1" },
  Jeep:      { accent: "#424D07", visible: "#424D07", ink: "#e3ef9a" },
  Ram:       { accent: "#767676", visible: "#767676", ink: "#eeeeee" },
  Toyota:    { accent: "#eb0a1e", visible: "#eb0a1e", ink: "#ffe0e0" },
  Buick:     { accent: "#005daa", visible: "#005daa", ink: "#c9e0ff" },
  Chevrolet: { accent: "#c8a95a", visible: "#a07a20", ink: "#fff4d8" },
  GMC:       { accent: "#005daa", visible: "#005daa", ink: "#c9e0ff" },
  Ford:      { accent: "#003478", visible: "#003478", ink: "#c9d8ff" },
  Nissan:    { accent: "#c3002f", visible: "#c3002f", ink: "#ffe0e8" },
  Subaru:    { accent: "#013c74", visible: "#013c74", ink: "#c9deff" },
  RAM:       { accent: "#767676", visible: "#767676", ink: "#eeeeee" },
};

const transitions = {
  needs_seo: [["seo_in_progress", "Start SEO"], ["seo_done", "Mark SEO done"], ["ignored", "Ignore"], ["snoozed", "Snooze"]],
  seo_in_progress: [["seo_done", "Mark SEO done"], ["needs_seo", "Unclaim"]],
  seo_done: [["needs_build", "Send To Build"], ["live", "Mark Already Live"]],
  needs_build: [["page_built", "Mark Page Built"], ["seo_done", "Return To SEO Done"]],
  page_built: [["live", "Mark Page Live"], ["needs_build", "Reopen"]],
  live: [["needs_review", "Review Page"]],
  ignored: [["needs_seo", "Restore"]],
  snoozed: [["needs_seo", "Unsnooze"]],
  needs_review: [["needs_seo", "Send Back To SEO"], ["live", "Keep Live"]],
};

// ─── SEO doc links — keyed by "dealer|year" ──────────────────────────────────
// Update this when new SEO docs are created. One doc per dealer per model year.
const SEO_DOC_LINKS = {
  // 2026
  "Lou Fusz Buick GMC|2026|Buick":              "https://docs.google.com/document/d/1MBGavCiv5hPRu-tUQbAaljgpSIj3qINTDh38IvHULcg",
  "Lou Fusz Buick GMC|2026|GMC":                "https://docs.google.com/document/d/1NazVn5GX5biK4-9hRrhu3JA6s8lmMfm_nZv_o1EDhpg",
  "Lou Fusz Chevrolet|2026":                    "https://docs.google.com/document/d/1r9Cq1zmY5KNOKFFCtHPr3QaxxhtUAd-yNUzeOK3rv_g",
  "Lou Fusz Chrysler Jeep Dodge RAM|2026":      "https://docs.google.com/document/d/1K9yfKp35prou0dmO2PCyqidQtX7zbm12ESDkaSl31f0",
  "Lou Fusz Chrysler Jeep Dodge Ram Vincennes|2026": "https://docs.google.com/document/d/1G_BK4uhSpbu3cckxEMMKmWxVsWo3bqbmNkYmOWKKUBc",
  "Lou Fusz Ford|2026":                         "https://docs.google.com/document/d/1t0L_M5lIHyzL70rTRtL-GxT93EqjluMlVbtbFO6wQwA",
  "Lou Fusz Kia|2026":                          "https://docs.google.com/document/d/1NlWYTeT7Z8ncs4MLlpf4h0Kh4-rYKFVjt4SZCARKeNQ",
  "Lou Fusz Kia Evansville|2026":               "https://docs.google.com/document/d/1kLiBmdTgEj37av8WjQ2AyoELfWZpa7rP-nDh9hQenow",
  "Lou Fusz Kia of Moline|2026":                "https://docs.google.com/document/d/1432gqSwCj522lFQOb6cORiWiDnjm22R5q1DXwWjjQx8",
  "Lou Fusz Kia Terre Haute|2026":              "https://docs.google.com/document/d/1bKVl7pnVmd3MBl3Q-AiKqUZ0xphg1ZWsaSpb15syhps",
  "Lou Fusz Kia Columbus|2026":                 "https://docs.google.com/document/d/1Z3RK7-VVsyfQH4rERoxhB73eE2KdZ632Prw0EgfbRmU",
  "Lou Fusz Mazda|2026":                        "https://docs.google.com/document/d/17JROHls8DDvVEOq2o3hoQ7EmX3yhH8ztuAxLaCKDnXU",
  "Lou Fusz Mazda Evansville|2026":             "https://docs.google.com/document/d/1OSW_dubcbnbHvO42NdRKGO-JnVWKk1aarryx72EVzhg",
  "Lou Fusz Nissan Moline|2026":                "https://docs.google.com/document/d/1lmGvBu5w87lH2TxhCyAc5BLKo8h7J7UjPwzFpKmAjbk",
  "Lou Fusz Subaru O'Fallon|2026":              "https://docs.google.com/document/d/11R3OLIuDFqmHioRA6-Hp-Z6env0wu1pYNB46ccOX-Lo",
  "Lou Fusz Subaru St. Louis|2026":             "https://docs.google.com/document/d/1COvqcNa-kRR48OwghYip_AQfqPOBws1A9dsNtHHVlZY",
  "Lou Fusz Toyota|2026":                       "https://docs.google.com/document/d/1Tac7AcuSyyvR2gOWA-RDu2q0-yGXBvqtVSKM9-OVZbQ",
  // 2027
  "Lou Fusz Chevrolet|2027":                    "https://docs.google.com/document/d/1H-asB_sMbrXT6Oqz2B-H9qv3zVPPi2L9Sp6nYFBGEK4",
  "Lou Fusz Chrysler Jeep Dodge RAM|2027":      "https://docs.google.com/document/d/12OdXuRYK3yDaz1B4TutqavuuE4WmrNiIpreguow4GDQ",
  "Lou Fusz Chrysler Jeep Dodge Ram Vincennes|2027": "https://docs.google.com/document/d/1nRrjzbD4l_lHRdZ1DSPPDvSsODOSxijA3F9_XA3pMIY",
  "Lou Fusz Kia|2027":                          "https://docs.google.com/document/d/17Llp8wDE_uX18dauWdGjq_zmN5NlgTCUUvBzcRcPk8s",
  "Lou Fusz Kia Evansville|2027":               "https://docs.google.com/document/d/1Zn6tmMcljwn3ZMm78F1xd4xMWwR7LqMmRJ_k7-wryiU",
  "Lou Fusz Kia Terre Haute|2027":              "https://docs.google.com/document/d/1dMO9YK7xE7SPC-dpD-tyi9Rby9l_dGAP2USB9VBhtVA",
  "Lou Fusz Kia of Moline|2027":                "https://docs.google.com/document/d/1yai_qzf600AQAJf8-CGtOoHcMcfdc5fXILQGDrsRHTI",
  "Lou Fusz Kia Columbus|2027":                 "https://docs.google.com/document/d/1NROowSjtBxbwDpsNSzSk1VF6VNDacnByun6pO_XqXzc",
};

function seoDocUrl(task) {
  if (!task) return null;
  const dealer = task.dealer || "";
  const year = task.year || "";
  const make = task.make || "";
  // Try dealer|year|make first (for Buick GMC which has two docs), then dealer|year
  return SEO_DOC_LINKS[`${dealer}|${year}|${make}`]
      || SEO_DOC_LINKS[`${dealer}|${year}`]
      || null;
}

const embeddedTracker = [
  // ─── 2026 completed pages (179 pages · imported from tracker) ───
{ id: "lou-fusz-mazda|2026|cx-5", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "CX-5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|crown", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Crown", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|carnival-hybrid", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "Carnival (Hybrid)", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|trailblazer", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Trailblazer", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|mustang", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Mustang", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|carnival-hybrid", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "Carnival (Hybrid)", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|carnival-hybrid", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "Carnival (Hybrid)", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|carnival-hybrid", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "Carnival (Hybrid)", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|cx-5", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "CX-5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|leaf", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "LEAF", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|forester", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Forester", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|forester", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Forester", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|carnival-hybrid", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "Carnival (Hybrid)", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|pacifica", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Pacifica", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda3-hatchback", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda3 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|rav4", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "RAV4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|encore-gx", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Encore GX", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|ev9", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "EV9", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|equinox", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Equinox", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|expedition", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Expedition", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|pacifica", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Pacifica", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|ev9", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "EV9", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|ev9", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "EV9", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|ev9", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "EV9", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|mazda3-hatchback", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "Mazda3 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|armada", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Armada", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|crosstrek-hybrid", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Crosstrek Hybrid", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|crosstrek-hybrid", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Crosstrek Hybrid", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|ev9", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "EV9", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|voyager", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Voyager", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-cx-90", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda CX-90", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|rav4-plug-in-hybrid", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "RAV4 Plug in Hybrid", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|envista", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Envista", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|seltos", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "Seltos", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|explorer", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Explorer", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|voyager", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Voyager", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|seltos", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "Seltos", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|seltos", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "Seltos", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|seltos", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "Seltos", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|cx-90", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "CX-90", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|murano", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Murano", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|solterra", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Solterra", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|solterra", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Solterra", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|seltos", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "Seltos", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-cx-50", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda CX-50", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|bz", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "bZ", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|envision", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Envision", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|sportage", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "Sportage", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|corvette-stingray", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Corvette Stingray", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|escape", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Escape", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|sportage", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "Sportage", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|sportage", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "Sportage", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|sportage", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "Sportage", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|cx-30", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "CX-30", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|frontier", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Frontier", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|outback", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Outback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|outback", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Outback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|sportage", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "Sportage", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-cx-30", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda CX-30", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|c-hr", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "C-HR", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|enclave", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Enclave", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|k5", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "K5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|traverse", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Traverse", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|super-duty-f-250", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Super Duty F-250", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|k5", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "K5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|k5", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "K5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|k5", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "K5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|cx-50", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "CX-50", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|rogue", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Rogue", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|trailseeker", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Trailseeker", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|trailseeker", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Trailseeker", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|k5", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "K5", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|durango", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Durango", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda3-sedan", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda3 Sedan", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|corolla-hatchback", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Corolla Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|k4-hatchback", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "K4 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|silverado-1500", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Silverado 1500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|maverick", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Maverick", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|durango", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Durango", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|k4-hatchback", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "K4 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|k4-hatchback", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "K4 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|k4-hatchback", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "K4 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|cx-70", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "CX-70", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|kicks", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Kicks", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|uncharted", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Uncharted", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|uncharted", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Uncharted", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|k4-hatchback", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "K4 Hatchback", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|charger", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Charger", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-cx-70", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda CX-70", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|corolla-cross", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Corolla Cross", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|terrain", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Terrain", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|k4", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "K4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|colorado", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Colorado", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|f-150", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "F-150", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|dodge-charger", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Dodge Charger", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|k4", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "K4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|k4", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "K4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|k4", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "K4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|mazda3-sedan", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "Mazda3 Sedan", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|sentra", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Sentra", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|impreza", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Impreza", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|impreza", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Impreza", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|k4", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "K4", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-mx-5-miata", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda MX-5 MIATA", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|gr86", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "GR86", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|sierra-ev", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Sierra EV", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|sorento", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "Sorento", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|suburban", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Suburban", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|ranger", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Ranger", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|sorento", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "Sorento", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|sorento", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "Sorento", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|sorento", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "Sorento", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|mazda-mx-5-miata", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "Mazda MX-5 MIATA", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|pathfinder", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Pathfinder", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|ascent", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "Ascent", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|ascent", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "Ascent", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|sorento", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "Sorento", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda|2026|mazda-mx-5-miata-rf", dealer: "Lou Fusz Mazda", year: 2026, make: "Mazda", model: "Mazda MX-5 MIATA RF", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|camry", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Camry", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|hummer-ev-suv", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Hummer EV SUV", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2026|niro", dealer: "Lou Fusz Kia", year: 2026, make: "Kia", model: "Niro", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|trax", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Trax", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|bronco", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Bronco", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2026|niro", dealer: "Lou Fusz Kia Evansville", year: 2026, make: "Kia", model: "Niro", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2026|niro", dealer: "Lou Fusz Kia of Moline", year: 2026, make: "Kia", model: "Niro", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2026|niro", dealer: "Lou Fusz Kia Terre Haute", year: 2026, make: "Kia", model: "Niro", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-mazda-evansville|2026|mazda-mx-5-miata-rf", dealer: "Lou Fusz Mazda Evansville", year: 2026, make: "Mazda", model: "Mazda MX-5 MIATA RF", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|altima", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Altima", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|brz", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "BRZ", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|brz", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "BRZ", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2026|niro", dealer: "Lou Fusz Kia Columbus", year: 2026, make: "Kia", model: "Niro", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|cherokee", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Cherokee", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|corolla", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Corolla", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|acadia", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Acadia", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|equinox-ev", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Equinox EV", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|bronco-sport", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Bronco Sport", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|cherokee", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Cherokee", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|murano", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Murano", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-st-louis|2026|wrx", dealer: "Lou Fusz Subaru St. Louis", year: 2026, make: "Subaru", model: "WRX", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-subaru-o-fallon|2026|wrx", dealer: "Lou Fusz Subaru O'Fallon", year: 2026, make: "Subaru", model: "WRX", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|compass", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Compass", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|grand-highlander", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Grand HIghlander", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|canyon", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Canyon", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|tahoe", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Tahoe", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-ford|2026|mustang-mach-e", dealer: "Lou Fusz Ford", year: 2026, make: "Ford", model: "Mustang Mach-E", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|compass", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Compass", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-nissan-moline|2026|z", dealer: "Lou Fusz Nissan Moline", year: 2026, make: "Nissan", model: "Z", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|wrangler", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Wrangler", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|tundra", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Tundra", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|yukon-xl", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Yukon XL", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|silverado-2500", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Silverado 2500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|gladiator", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Gladiator", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|gladiator", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Gladiator", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|prius", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Prius", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|sierra-1500", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Sierra 1500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|blazer", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Blazer", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|wrangler", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Wrangler", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|grand-cherokee", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Grand Cherokee", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|sequoia", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Sequoia", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|sierra-2500", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Sierra 2500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chevrolet|2026|blazer-ev", dealer: "Lou Fusz Chevrolet", year: 2026, make: "Chevrolet", model: "Blazer EV", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|grand-cherokee", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Grand Cherokee", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|grand-wagoneer", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "Grand Wagoneer", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|gr-supra", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "GR Supra", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|yukon", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Yukon", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|grand-wagoneer", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "Grand Wagoneer", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|land-crsuier", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Land Crsuier", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-buick-gmc|2026|hummer-ev-pickup", dealer: "Lou Fusz Buick GMC", year: 2026, make: "Buick", model: "Hummer EV Pickup", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|1500", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "1500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|highlander", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Highlander", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|sienna", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Sienna", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2026|2500", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2026, make: "Chrysler", model: "2500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|4runner", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "4Runner", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|gr-corolla", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "GR Corolla", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-toyota|2026|tacoma", dealer: "Lou Fusz Toyota", year: 2026, make: "Toyota", model: "Tacoma", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|1500", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "1500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|1500-rho", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "1500 RHO", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|2500", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "2500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2026|3500", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2026, make: "Chrysler", model: "3500", pageStatus: "live", aeoStatus: "not_needed", details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },

  // ─── 2027 active pipeline ───
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2027|pacifica", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2027, make: "Chrysler", model: "Pacifica", pageStatus: "live", trackerStatusRaw: true, trackerRow: 3, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2027|1500-srt-trx", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2027, make: "Ram", model: "1500 SRT TRX", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 18, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-mazda|2027|mazda-cx-50", dealer: "Lou Fusz Mazda", year: 2027, make: "Mazda", model: "Mazda CX-50", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 5, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-mazda|2027|mazda-cx-70", dealer: "Lou Fusz Mazda", year: 2027, make: "Mazda", model: "Mazda CX-70", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 8, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-toyota|2027|land-cruiser", dealer: "Lou Fusz Toyota", year: 2027, make: "Toyota", model: "Land Cruiser", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 2, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-toyota|2027|highlander-ev", dealer: "Lou Fusz Toyota", year: 2027, make: "Toyota", model: "Highlander EV", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 18, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-buick-gmc|2027|terrain", dealer: "Lou Fusz Buick GMC", year: 2027, make: "GMC", model: "Terrain", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 8, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-buick-gmc|2027|sierra-1500", dealer: "Lou Fusz Buick GMC", year: 2027, make: "GMC", model: "Sierra 1500", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 11, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia|2027|kia-telluride", dealer: "Lou Fusz Kia", year: 2027, make: "Kia", model: "Kia Telluride", pageStatus: "live", trackerStatusRaw: true, trackerRow: 2, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia|2027|seltos", dealer: "Lou Fusz Kia", year: 2027, make: "Kia", model: "Seltos", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia|2027|ev3", dealer: "Lou Fusz Kia", year: 2027, make: "Kia", model: "EV3", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chevrolet|2027|equinox", dealer: "Lou Fusz Chevrolet", year: 2027, make: "Chevrolet", model: "Equinox", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chevrolet|2027|silverado-1500", dealer: "Lou Fusz Chevrolet", year: 2027, make: "Chevrolet", model: "Silverado 1500", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 7, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chevrolet|2027|bolt", dealer: "Lou Fusz Chevrolet", year: 2027, make: "Chevrolet", model: "Bolt", pageStatus: "live", trackerStatusRaw: true, trackerRow: 13, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2027|pacifica", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2027, make: "Chrysler", model: "Pacifica", pageStatus: "live", trackerStatusRaw: true, trackerRow: 3, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-chrysler-jeep-dodge-ram-vincennes|2027|1500-srt-trx", dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", year: 2027, make: "Ram", model: "1500 SRT TRX", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 24, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-evansville|2027|kia-telluride", dealer: "Lou Fusz Kia Evansville", year: 2027, make: "Kia", model: "Kia Telluride", pageStatus: "live", trackerStatusRaw: true, trackerRow: 2, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-evansville|2027|seltos", dealer: "Lou Fusz Kia Evansville", year: 2027, make: "Kia", model: "Seltos", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-evansville|2027|ev3", dealer: "Lou Fusz Kia Evansville", year: 2027, make: "Kia", model: "EV3", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-of-moline|2027|kia-telluride", dealer: "Lou Fusz Kia of Moline", year: 2027, make: "Kia", model: "Kia Telluride", pageStatus: "live", trackerStatusRaw: true, trackerRow: 2, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-of-moline|2027|seltos", dealer: "Lou Fusz Kia of Moline", year: 2027, make: "Kia", model: "Seltos", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-of-moline|2027|ev3", dealer: "Lou Fusz Kia of Moline", year: 2027, make: "Kia", model: "EV3", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-terre-haute|2027|kia-telluride", dealer: "Lou Fusz Kia Terre Haute", year: 2027, make: "Kia", model: "Kia Telluride", pageStatus: "live", trackerStatusRaw: true, trackerRow: 2, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-terre-haute|2027|seltos", dealer: "Lou Fusz Kia Terre Haute", year: 2027, make: "Kia", model: "Seltos", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-terre-haute|2027|ev3", dealer: "Lou Fusz Kia Terre Haute", year: 2027, make: "Kia", model: "EV3", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-mazda-evansville|2027|mazda-cx-50", dealer: "Lou Fusz Mazda Evansville", year: 2027, make: "Mazda", model: "Mazda CX-50", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 2, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-mazda-evansville|2027|mazda-cx-70", dealer: "Lou Fusz Mazda Evansville", year: 2027, make: "Mazda", model: "Mazda CX-70", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 9, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-nissan-moline|2027|nissan-z", dealer: "Lou Fusz Nissan Moline", year: 2027, make: "Nissan", model: "Nissan Z", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 5, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-st.-louis|2027|crosstrek", dealer: "Lou Fusz Subaru St. Louis", year: 2027, make: "Subaru", model: "Crosstrek", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 2, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-st.-louis|2027|crosstrek-hybrid", dealer: "Lou Fusz Subaru St. Louis", year: 2027, make: "Subaru", model: "Crosstrek Hybrid", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-st.-louis|2027|getaway-ev", dealer: "Lou Fusz Subaru St. Louis", year: 2027, make: "Subaru", model: "Getaway EV", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-o'fallon|2027|crosstrek", dealer: "Lou Fusz Subaru O'Fallon", year: 2027, make: "Subaru", model: "Crosstrek", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 2, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-o'fallon|2027|crosstrek-hybrid", dealer: "Lou Fusz Subaru O'Fallon", year: 2027, make: "Subaru", model: "Crosstrek Hybrid", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-subaru-o'fallon|2027|getaway-ev", dealer: "Lou Fusz Subaru O'Fallon", year: 2027, make: "Subaru", model: "Getaway EV", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-columbus|2027|kia-telluride", dealer: "Lou Fusz Kia Columbus", year: 2027, make: "Kia", model: "Kia Telluride", pageStatus: "live", trackerStatusRaw: true, trackerRow: 2, source: "sharepoint-2027-tracker" , details: { buildOwner: "Jnuru Goodwin", seoOwner: "Chris Pajda" } },
  { id: "lou-fusz-kia-columbus|2027|seltos", dealer: "Lou Fusz Kia Columbus", year: 2027, make: "Kia", model: "Seltos", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 3, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia-columbus|2027|ev3", dealer: "Lou Fusz Kia Columbus", year: 2027, make: "Kia", model: "EV3", pageStatus: "needs_seo", trackerStatusRaw: null, trackerRow: 4, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-toyota|2027|camry", dealer: "Lou Fusz Toyota", year: 2027, make: "Toyota", model: "Camry", pageStatus: "seo_done", trackerStatusRaw: null, trackerRow: 5, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-toyota|2027|rav4", dealer: "Lou Fusz Toyota", year: 2027, make: "Toyota", model: "RAV4", pageStatus: "seo_done", trackerStatusRaw: null, trackerRow: 6, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chevrolet|2027|trax", dealer: "Lou Fusz Chevrolet", year: 2027, make: "Chevrolet", model: "Trax", pageStatus: "seo_done", trackerStatusRaw: null, trackerRow: 9, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-ford|2027|bronco", dealer: "Lou Fusz Ford", year: 2027, make: "Ford", model: "Bronco", pageStatus: "seo_done", trackerStatusRaw: null, trackerRow: 6, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-mazda|2027|cx-5", dealer: "Lou Fusz Mazda", year: 2027, make: "Mazda", model: "CX-5", pageStatus: "needs_build", trackerStatusRaw: null, trackerRow: 10, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-kia|2027|sportage", dealer: "Lou Fusz Kia", year: 2027, make: "Kia", model: "Sportage", pageStatus: "needs_build", trackerStatusRaw: null, trackerRow: 6, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-buick-gmc|2027|acadia", dealer: "Lou Fusz Buick GMC", year: 2027, make: "GMC", model: "Acadia", pageStatus: "needs_build", trackerStatusRaw: null, trackerRow: 14, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chrysler-jeep-dodge-ram|2027|wrangler", dealer: "Lou Fusz Chrysler Jeep Dodge RAM", year: 2027, make: "Jeep", model: "Wrangler", pageStatus: "needs_build", trackerStatusRaw: null, trackerRow: 9, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-ford|2027|f-150-lightning", dealer: "Lou Fusz Ford", year: 2027, make: "Ford", model: "F-150 Lightning", pageStatus: "page_built", trackerStatusRaw: null, trackerRow: 8, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-toyota|2027|4runner", dealer: "Lou Fusz Toyota", year: 2027, make: "Toyota", model: "4Runner", pageStatus: "page_built", trackerStatusRaw: null, trackerRow: 9, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-chevrolet|2027|tahoe", dealer: "Lou Fusz Chevrolet", year: 2027, make: "Chevrolet", model: "Tahoe", pageStatus: "page_built", trackerStatusRaw: null, trackerRow: 11, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-buick-gmc|2027|yukon", dealer: "Lou Fusz Buick GMC", year: 2027, make: "GMC", model: "Yukon", pageStatus: "needs_review", trackerStatusRaw: null, trackerRow: 15, source: "sharepoint-2027-tracker" },
  { id: "lou-fusz-ford|2027|mustang-mach-e", dealer: "Lou Fusz Ford", year: 2027, make: "Ford", model: "Mustang Mach-E", pageStatus: "needs_review", trackerStatusRaw: null, trackerRow: 10, source: "sharepoint-2027-tracker" },
];

const embeddedSources = [
  { dealer: "Lou Fusz Chrysler Jeep Dodge RAM", shortName: "CJDR", brands: ["Chrysler", "Dodge", "Jeep", "Ram"], inventoryUrl: "https://www.loufuszchryslerjeepdodge.net/new-vehicles/" },
  { dealer: "Lou Fusz Mazda", shortName: "Mazda", brands: ["Mazda"], inventoryUrl: "https://www.mazda.fusz.com/new-vehicles/" },
  { dealer: "Lou Fusz Toyota", shortName: "Toyota", brands: ["Toyota"], inventoryUrl: "https://www.fusztoyota.com/new-vehicles/" },
  { dealer: "Lou Fusz Buick GMC", shortName: "Buick GMC", brands: ["Buick", "GMC"], inventoryUrl: "https://www.loufuszbuickgmc.com/new-vehicles/" },
  { dealer: "Lou Fusz Chevrolet", shortName: "Chevrolet", brands: ["Chevrolet"], inventoryUrl: "https://www.loufuszchevrolet.com/new-vehicles/" },
  { dealer: "Lou Fusz Kia", shortName: "Kia", brands: ["Kia"], inventoryUrl: "https://www.kia.fusz.com/new-vehicles/" },
  { dealer: "Lou Fusz Ford", shortName: "Ford", brands: ["Ford"], inventoryUrl: "https://www.loufuszford.com/new-vehicles/" },
  { dealer: "Lou Fusz Chrysler Jeep Dodge Ram Vincennes", shortName: "CJDR Vincennes", brands: ["Chrysler", "Dodge", "Jeep", "Ram"], inventoryUrl: "https://www.loufuszcjdrvincennes.com/new-vehicles/" },
  { dealer: "Lou Fusz Kia Evansville", shortName: "Kia Evansville", brands: ["Kia"], inventoryUrl: "https://www.evansvillekia.com/" },
  { dealer: "Lou Fusz Kia of Moline", shortName: "Kia Moline", brands: ["Kia"], inventoryUrl: "https://www.loufuszkiamoline.com/new-vehicles/" },
  { dealer: "Lou Fusz Kia Terre Haute", shortName: "Kia Terre Haute", brands: ["Kia"], inventoryUrl: "https://www.loufuszkiaterrehaute.com/new-vehicles/" },
  { dealer: "Lou Fusz Mazda Evansville", shortName: "Mazda Evansville", brands: ["Mazda"], inventoryUrl: "https://www.loufuszmazdaevansville.com/new-vehicles/" },
  { dealer: "Lou Fusz Nissan Moline", shortName: "Nissan Moline", brands: ["Nissan"], inventoryUrl: "https://www.loufusznissanmoline.com/new-vehicles/" },
  { dealer: "Lou Fusz Subaru St. Louis", shortName: "Subaru St. Louis", brands: ["Subaru"], inventoryUrl: "https://www.subaru.fusz.com/new-vehicles/" },
  { dealer: "Lou Fusz Subaru O'Fallon", shortName: "Subaru O'Fallon", brands: ["Subaru"], inventoryUrl: "https://www.fuszsubaru.com/new-vehicles/" },
  { dealer: "Lou Fusz Kia Columbus", shortName: "Kia Columbus", brands: ["Kia"], inventoryUrl: "https://www.loufuszkia.com/new-vehicles/" },
];

