const storedThemeChoice = localStorage.getItem("fusz-theme");
const isDemoReset = new URLSearchParams(window.location.search).get("demo") === "reset";
const initialThemeChoice = isDemoReset
  ? "light"
  : ["system", "light", "dark", "gray"].includes(storedThemeChoice)
    ? (storedThemeChoice === "gray" ? "dark" : storedThemeChoice)
    : "system";

const state = {
  tasks: [],
  sources: [],
  inventoryFeed: {
    connected: false,
    rows: [],
    message: "Waiting on CSV",
  },
  session: JSON.parse(localStorage.getItem("fusz-demo-session") || "null"),
  overrides: JSON.parse(localStorage.getItem("pipeline-status-overrides") || "{}"),
  aeoOverrides: JSON.parse(localStorage.getItem("pipeline-aeo-overrides") || "{}"),
  details: JSON.parse(localStorage.getItem("pipeline-task-details") || "{}"),
  signalOverrides: JSON.parse(localStorage.getItem("pipeline-signal-overrides") || "{}"),
  rooftops: JSON.parse(localStorage.getItem("fusz-rooftops") || "null"),
  driveConnection: localStorage.getItem("fusz-drive-connection") || "not_connected",
  workspaceView: localStorage.getItem("pipeline-workspace-view") || "my_work",
  onboardingStep: "login",
  selectedTheme: initialThemeChoice,
  activeTaskId: null,
};


const els = {
  authScreen: document.querySelector("#authScreen"),
  authCards: document.querySelectorAll("[data-auth-step]"),
  flowDots: document.querySelectorAll("[data-flow-dot]"),
  continueLoginButton: document.querySelector("#continueLoginButton"),
  previewAdminButton: document.querySelector("#previewAdminButton"),
  continueThemeButton: document.querySelector("#continueThemeButton"),
  enterWorkspaceButton: document.querySelector("#enterWorkspaceButton"),
  skipToBoardButton: document.querySelector("#skipToBoardButton"),
  themeOptions: document.querySelectorAll("[data-theme-choice]"),
  restartDemoButton: document.querySelector("#restartDemoButton"),
  userContext: document.querySelector("#userContext"),
  pageTitle: document.querySelector("#pageTitle"),
  rolePill: document.querySelector("#rolePill"),
  mobileMenuButton: document.querySelector("#mobileMenuButton"),
  navCloseButton: document.querySelector("#navCloseButton"),
  navBackdrop: document.querySelector("#navBackdrop"),
  yearFilter: document.querySelector("#yearFilter"),
  dealerFilter: document.querySelector("#dealerFilter"),
  statusFilter: document.querySelector("#statusFilter"),
  clearFiltersButton: document.querySelector("#clearFiltersButton"),
  searchInput: document.querySelector("#searchInput"),
  seoQueue: document.querySelector("#seoQueue"),
  aeoQueue: document.querySelector("#aeoQueue"),
  buildQueue: document.querySelector("#buildQueue"),
  taskTable: document.querySelector("#taskTable"),
  tableTitle: document.querySelector("#tableTitle"),
  seoCount: document.querySelector("#seoCount"),
  aeoCount: document.querySelector("#aeoCount"),
  buildCount: document.querySelector("#buildCount"),
  visibleCount: document.querySelector("#visibleCount"),
  metricDetected: document.querySelector("#metricDetected"),
  metricSeo: document.querySelector("#metricSeo"),
  metricAeo: document.querySelector("#metricAeo"),
  metricLive: document.querySelector("#metricLive"),
  achievementWritten: document.querySelector("#achievementWritten"),
  achievementLive: document.querySelector("#achievementLive"),
  achievementRemaining: document.querySelector("#achievementRemaining"),
  scanButton: document.querySelector("#scanButton"),
  digestButton: document.querySelector("#digestButton"),
  workspaceButtons: document.querySelectorAll("[data-workspace-view]"),
  focusPanel: document.querySelector("#focusPanel"),
  focusTitle: document.querySelector("#focusTitle"),
  focusMeta: document.querySelector("#focusMeta"),
  focusTags: document.querySelector("#focusTags"),
  focusActions: document.querySelector("#focusActions"),
  myWorkPanel: document.querySelector("#myWorkPanel"),
  myWorkList: document.querySelector("#myWorkList"),
  myWorkCount: document.querySelector("#myWorkCount"),
  builderDetailPanel: document.querySelector("#builderDetailPanel"),
  builderDetailContent: document.querySelector("#builderDetailContent"),
  adminPanel: document.querySelector("#adminPanel"),
  rooftopsManager: document.querySelector("#rooftopsManager"),
  rooftopsList: document.querySelector("#rooftopsList"),
  addRooftopButton: document.querySelector("#addRooftopButton"),
  upcomingPanel: document.querySelector("#upcomingPanel"),
  upcomingList: document.querySelector("#upcomingList"),
  upcomingCount: document.querySelector("#upcomingCount"),
  docsPanel: document.querySelector("#docsPanel"),
  docsDigestButton: document.querySelector("#docsDigestButton"),
  digestDialog: document.querySelector("#digestDialog"),
  digestText: document.querySelector("#digestText"),
  taskDialog: document.querySelector("#taskDialog"),
  taskDialogTitle: document.querySelector("#taskDialogTitle"),
  detailSignalSelect: document.querySelector("#detailSignalSelect"),
  detailAeoSelect: document.querySelector("#detailAeoSelect"),
  seoOwnerInput: document.querySelector("#seoOwnerInput"),
  aeoOwnerInput: document.querySelector("#aeoOwnerInput"),
  buildOwnerInput: document.querySelector("#buildOwnerInput"),
  taskNotesInput: document.querySelector("#taskNotesInput"),
  saveTaskDetailsButton: document.querySelector("#saveTaskDetailsButton"),
  settingsAvatar: document.querySelector("#settingsAvatar"),
  settingsName: document.querySelector("#settingsName"),
  settingsRole: document.querySelector("#settingsRole"),
  settingsLandingSelect: document.querySelector("#settingsLandingSelect"),
  settingsThemeSelect: document.querySelector('[aria-labelledby="accountSettingsTitle"] .settings-row:last-of-type select'),
  settingsAccessBadges: document.querySelector("#settingsAccessBadges"),
  driveConnectionStatus: document.querySelector("#driveConnectionStatus"),
  connectDriveButton: document.querySelector("#connectDriveButton"),
  feedVehicleCount: document.querySelector("#feedVehicleCount"),
  feedSampleVehicle: document.querySelector("#feedSampleVehicle"),
  feedConnectionStatus: document.querySelector("#feedConnectionStatus"),
  toast: document.querySelector("#toast"),
};
